image: Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  SONARCLOUD_PROJECT_KEY: RHEAGROUP_CDP4-SDK-Community-Edition
  SONARCLOUD_ORGANIZATION: rheagroup
  SONARCLOUD_TOKEN:
    secure: t9Adl8VvYx+PRNMC3aXmpSErjxmh/LaCV52WW1X/IxGgjkGYRTf7ZYcNs4s3Fqrt

skip_branch_with_pr: true

for:
# configuration for "master" branch, build in Release mode
-
  branches:
    only:
      - master
  configuration: Release
# configuration for "development" branch, build in Debug mode
-
  branches:
    only:
      - development
  configuration: Debug
# "fall back" configuration for all other branches
# no "branches" section defined
configuration: Debug
install:
  - choco install "sonarscanner-msbuild-net46" -y
  - choco install opencover -y
before_build:
  - cmd: nuget restore
  - ps: >-
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER){
        Write-Host Scanning PR: $env:APPVEYOR_PULL_REQUEST_NUMBER
        SonarScanner.MSBuild.exe begin /key:$env:SONARCLOUD_PROJECT_KEY /o:$env:SONARCLOUD_ORGANIZATION /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$env:SONARCLOUD_TOKEN /d:sonar.pullrequest.key=$env:APPVEYOR_PULL_REQUEST_NUMBER /d:sonar.pullrequest.provider=GitHub /d:sonar.pullrequest.github.repository=$env:APPVEYOR_REPO_NAME
      }
      else {
        Write-Host Scanning branch: $env:APPVEYOR_REPO_BRANCH
        SonarScanner.MSBuild.exe begin /key:$env:SONARCLOUD_PROJECT_KEY /o:$env:SONARCLOUD_ORGANIZATION /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=$env:SONARCLOUD_TOKEN
      }
build:
  project: CDP4-SDK.sln
test:
  assemblies:
    only:
      - '**\bin\$(configuration)\net472\*.Tests.dll'
      - '**\bin\$(configuration)\netstandard1.6\*.Tests.dll'
      - '**\bin\$(configuration)\netstandard2.0\*.Tests.dll'
  categories:
    except:
      - WebServicesDependent
      - AppVeyorExclusion
after_test:
  - ps: SonarScanner.MSBuild.exe end /d:"sonar.login=$env:SONARCLOUD_TOKEN"
notifications:
  - provider: Email
    to:
      - cdp_devs@rheagroup.com
