image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
- ps: |
    Write-Host "Installing NUnit 3.9.0..." -ForegroundColor Cyan -NoNewline
    $toolsPath = "$env:SYSTEMDRIVE\Tools"
    $nunitPath = "$env:SYSTEMDRIVE\Tools\NUnit3"
    Remove-Item $nunitPath -Recurse -Force
    $zipPath = "$($env:TEMP)\NUnit.Console-3.9.0.zip"
    (New-Object Net.WebClient).DownloadFile('https://github.com/nunit/nunit-console/releases/download/v3.9/NUnit.Console-3.9.0.zip', $zipPath)
    7z x $zipPath -y -o"$nunitPath" | Out-Null
    del $zipPath
    $zipPath = "$($env:TEMP)\Appveyor.NUnit3Logger.zip"
    (New-Object Net.WebClient).DownloadFile('https://www.appveyor.com/downloads/Appveyor.NUnit3Logger.zip', $zipPath)
    7z x $zipPath -y -o"$nunitPath\addins" | Out-Null
    Move-Item "$nunitPath\addins\appveyor.addins" "$nunitPath\appveyor.addins"
    del $zipPath
    Remove-Path "$nunitPath\bin"
    Add-Path "$nunitPath"
    Write-Host "NUnit 3.9.0 installed" -ForegroundColor Green

for:
# configuration for "master" branch, build in Release mode
-
  branches:
    only:
      - master
  configuration: Release
# configuration for "development" branch, build in Debug mode
-
  branches:
    only:
      - development
  configuration: Debug
# "fall back" configuration for all other branches
# no "branches" section defined
configuration: Debug
before_build:
  - cmd: nuget restore
build:
  project: CDP4-SDK.sln
test:
  assemblies:
    only:
      - '**\bin\$(configuration)\net472\*.Tests.dll'
      - '**\bin\$(configuration)\netstandard1.6\*.Tests.dll'
      - '**\bin\$(configuration)\netstandard2.0\*.Tests.dll'
  categories:
    except:
      - WebServicesDependent
      - AppVeyorExclusion